**Problem 2A**

In [2]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import torch
import torch.optim as optim
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://drive.google.com/uc?export=download&id=1r0gkZL9150nrhZOtz9fIbVGKMqe45fbG"
housing = pd.read_csv(url)


num_vars = ['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'parking']
df_new = housing[num_vars]
scaler = MinMaxScaler()
df_new[num_vars] = scaler.fit_transform(df_new[num_vars])
df_new.head()


/tmp/ipython-input-2460575492.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new[num_vars] = scaler.fit_transform(df_new[num_vars])


price      area  bedrooms  bathrooms   stories   parking
0  1.000000  0.396564       0.6   0.333333  0.666667  0.666667
1  0.909091  0.502405       0.6   1.000000  1.000000  1.000000
2  0.909091  0.571134       0.4   0.333333  0.333333  0.666667
3  0.906061  0.402062       0.6   0.333333  0.333333  1.000000
4  0.836364  0.396564       0.6   0.000000  0.333333  0.666667

In [3]:
X = df_new.iloc[:, 1:6].values
Y = df_new.iloc[:, 0].values
X = torch.tensor(X)
Y = torch.tensor(Y)

def model(X, W1, W2, W3, W4, W5, B):
    return W5*X[:,4] + W4*X[:,3] + W3*X[:,2] + W2*X[:,1] + W1*X[:,0] + B

def loss_fn(Y_1, Y):
    squared_diffs = (Y_1 - Y)**2
    return squared_diffs.mean()

W1 = torch.ones(())
W2 = torch.ones(())
W3 = torch.ones(())
W4 = torch.ones(())
W5 = torch.ones(())
B = torch.zeros(())

n_samples = X.shape[0]
n_val = int(0.2 * n_samples)
shuffled_indices = torch.randperm(n_samples)
train_indices = shuffled_indices[:-n_val]
val_indices = shuffled_indices[-n_val:]

train_X = X[train_indices]
train_Y = Y[train_indices]
val_X = X[val_indices]
val_Y = Y[val_indices]

def training_loop(n_epochs, optimizer, params, train_X, val_X, train_Y, val_Y):

    for epoch in range(1, n_epochs + 1):
        train_Y_p = model(train_X, *params)
        train_loss = loss_fn(train_Y_p, train_Y)

        val_Y_p = model(val_X, *params)
        val_loss = loss_fn(val_Y_p, val_Y)

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch % 500 == 0:
            print(f"Epoch {epoch}, Training loss {train_loss.item():.4f},"
                  f" Validation loss {val_loss.item():.4f}")

    return params

In [5]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 0.1
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 0.0110, Validation loss 0.0134
Epoch 1000, Training loss 0.0110, Validation loss 0.0134
Epoch 1500, Training loss 0.0110, Validation loss 0.0134
Epoch 2000, Training loss 0.0110, Validation loss 0.0134
Epoch 2500, Training loss 0.0110, Validation loss 0.0134
Epoch 3000, Training loss 0.0110, Validation loss 0.0134
Epoch 3500, Training loss 0.0110, Validation loss 0.0134
Epoch 4000, Training loss 0.0110, Validation loss 0.0134
Epoch 4500, Training loss 0.0110, Validation loss 0.0134
Epoch 5000, Training loss 0.0110, Validation loss 0.0134


tensor([0.4363, 0.0423, 0.2724, 0.1505, 0.0954, 0.0505], requires_grad=True)

In [6]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 0.01
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)


Epoch 500, Training loss 0.0131, Validation loss 0.0149
Epoch 1000, Training loss 0.0112, Validation loss 0.0133
Epoch 1500, Training loss 0.0110, Validation loss 0.0134
Epoch 2000, Training loss 0.0110, Validation loss 0.0134
Epoch 2500, Training loss 0.0110, Validation loss 0.0134
Epoch 3000, Training loss 0.0110, Validation loss 0.0134
Epoch 3500, Training loss 0.0110, Validation loss 0.0134
Epoch 4000, Training loss 0.0110, Validation loss 0.0134
Epoch 4500, Training loss 0.0110, Validation loss 0.0134
Epoch 5000, Training loss 0.0110, Validation loss 0.0134


tensor([0.4363, 0.0423, 0.2724, 0.1505, 0.0954, 0.0505], requires_grad=True)

In [7]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 0.001
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)


Epoch 500, Training loss 0.1294, Validation loss 0.1139
Epoch 1000, Training loss 0.0523, Validation loss 0.0460
Epoch 1500, Training loss 0.0345, Validation loss 0.0314
Epoch 2000, Training loss 0.0231, Validation loss 0.0221
Epoch 2500, Training loss 0.0171, Validation loss 0.0176
Epoch 3000, Training loss 0.0145, Validation loss 0.0158
Epoch 3500, Training loss 0.0132, Validation loss 0.0149
Epoch 4000, Training loss 0.0125, Validation loss 0.0143
Epoch 4500, Training loss 0.0119, Validation loss 0.0137
Epoch 5000, Training loss 0.0115, Validation loss 0.0134


tensor([ 0.4655,  0.2079,  0.2246,  0.1264,  0.0848, -0.0092],
       requires_grad=True)

In [8]:
params = torch.tensor([1.0, 1.0, 1.0, 1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 0.0001
optimizer = optim.Adam([params], lr=learning_rate)

training_loop(
    n_epochs = 5000,
    optimizer = optimizer,
    params = params,
    train_X = train_X,
    val_X = val_X,
    train_Y = train_Y,
    val_Y = val_Y)

Epoch 500, Training loss 1.0080, Validation loss 0.9592
Epoch 1000, Training loss 0.8112, Validation loss 0.7681
Epoch 1500, Training loss 0.6454, Validation loss 0.6075
Epoch 2000, Training loss 0.5069, Validation loss 0.4737
Epoch 2500, Training loss 0.3927, Validation loss 0.3638
Epoch 3000, Training loss 0.3003, Validation loss 0.2752
Epoch 3500, Training loss 0.2273, Validation loss 0.2057
Epoch 4000, Training loss 0.1714, Validation loss 0.1529
Epoch 4500, Training loss 0.1304, Validation loss 0.1146
Epoch 5000, Training loss 0.1017, Validation loss 0.0883


tensor([ 0.6153,  0.6140,  0.5905,  0.5964,  0.5932, -0.3702],
       requires_grad=True)